"""
Knowledge Synthesis — M21.

Expresses Genesis's understanding of a concept as coherent language by
traversing the actual relation graph. This is the difference between
"Lately I've been thinking about wolves" (template pulling a name from
a spreadsheet) and a genuine first-person account of what Genesis
believes, why it believes it, and where its understanding is uncertain.

The output is built from:
    - Outgoing relations: what Genesis believes this concept does/causes/is
    - Causal chains: multi-hop paths that Genesis has traced
    - Evidence quality: corroboration count and source trust
    - Unresolved tensions: contradictions Genesis is holding
    - Active curiosity: what it still doesn't understand

No LLM API calls. All language is generated by traversing the graph
and filling relation-type-specific sentence frames with actual graph data.

The sentence frames are typed — each relation type (CAUSES, PREVENTS,
REQUIRES, IS_A, ...) has a distinct natural-language expression so the
output reads as understanding, not as a list of triples.
"""

import re
import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orchestrator.orchestrator import Orchestrator


# Minimum confidence to include in synthesis
_MIN_CONF = 0.45

# Maximum relations per concept before pruning to most salient
_MAX_RELS = 8

# Maximum chain depth to narrate
_MAX_CHAIN = 4

# Confidence tier labels
def _conf_label(conf: float) -> str:
    if conf >= 0.85:
        return "clearly"
    if conf >= 0.70:
        return "reliably"
    if conf >= 0.55:
        return "likely"
    return "possibly"


# Relation-type sentence frames.
# Each frame takes (subject, object, conf_label) and returns a clause.
_FRAMES: dict[str, str] = {
    "CAUSES":    "{subject} causes {object}",
    "PREVENTS":  "{subject} prevents {object}",
    "ENABLES":   "{subject} enables {object}",
    "REQUIRES":  "{subject} requires {object}",
    "CONTROLS":  "{subject} controls {object}",
    "IS_A":      "{subject} is a type of {object}",
    "AFFECTS":   "{subject} affects {object}",
    "CONTAINS":  "{subject} contains {object}",
    "PREDATES":  "{subject} predates {object}",
}

_DEFAULT_FRAME = "{subject} relates to {object}"


def _render(subject: str, rel_type: str, obj: str) -> str:
    frame = _FRAMES.get(rel_type, _DEFAULT_FRAME)
    return frame.format(subject=subject, object=obj)


class KnowledgeSynthesis:
    """
    Generates natural-language accounts of Genesis's understanding.

    Usage:
        ks = KnowledgeSynthesis(orchestrator)
        text = ks.explain("wolves")
        text = ks.reflect_on_state()   # full current-state summary
    """

    def __init__(self, orch: "Orchestrator"):
        self._orch = orch

    # ------------------------------------------------------------------
    # Primary entry points
    # ------------------------------------------------------------------

    def explain(self, concept: str) -> str:
        """
        What does Genesis understand about this concept?

        Traverses the relation graph, traces causal chains, checks for
        tensions and curiosity directives. Returns a coherent paragraph.
        """
        parts: list[str] = []

        # ── What does Genesis believe about this concept? ──────────────
        rels = self._orch.relations.query_subject(concept, min_confidence=_MIN_CONF)
        rels = sorted(rels, key=lambda r: r["confidence"], reverse=True)[:_MAX_RELS]

        if not rels:
            incoming = self._orch.relations.query_object(concept, min_confidence=_MIN_CONF)
            if not incoming:
                return (f"I have not yet formed a clear understanding of '{concept}'. "
                        f"It may be something I have encountered but not fully processed.")
            # Concept appears only as object — describe what leads to it
            parts.append(f"I know '{concept}' more as an outcome than a cause.")
            for r in incoming[:3]:
                clause = _render(r["subject"], r["relation"], concept)
                cl = _conf_label(r["confidence"])
                parts.append(f"I understand that {clause} ({cl}).")
        else:
            # Build the main understanding paragraph
            main_clauses: list[str] = []
            for r in rels[:4]:
                clause = _render(concept, r["relation"], r["object"])
                cl = _conf_label(r["confidence"])
                corr = self._orch.belief_revision.corroboration_factor(
                    concept, r["relation"], r["object"]
                )
                if corr >= 1.40:
                    # Independently corroborated — say so
                    n_sessions = round((corr - 1.0) / 0.20) + 1
                    main_clauses.append(
                        f"{clause} ({cl}, confirmed independently {n_sessions} times)"
                    )
                else:
                    main_clauses.append(f"{clause} ({cl})")

            if main_clauses:
                parts.append(
                    f"My understanding of '{concept}': "
                    + "; ".join(main_clauses) + "."
                )

        # ── Causal chains ──────────────────────────────────────────────
        chains = self._build_chains(concept)
        if chains:
            best = chains[0]
            if len(best) >= 2:
                chain_str = self._narrate_chain(best)
                parts.append(f"I can trace a chain: {chain_str}.")

        # ── Unresolved tensions ────────────────────────────────────────
        tensions = [
            t for t in self._orch.belief_revision.pending_tensions(limit=10)
            if t.get("subject") == concept
        ]
        if tensions:
            t = tensions[0]
            parts.append(
                f"I hold a tension I have not resolved: I have evidence that "
                f"'{concept}' both {t['rel_a'].lower()}s and "
                f"{t['rel_b'].lower()}s '{t['object']}'. "
                f"I am waiting for stronger evidence before deciding."
            )

        # ── Active curiosity ───────────────────────────────────────────
        directives = self._orch.curiosity_directives()
        if concept.lower() in [d.lower() for d in directives]:
            parts.append(
                f"'{concept}' is something I am actively trying to understand better — "
                f"I have encountered it in contexts I cannot yet fully explain."
            )

        return " ".join(parts) if parts else f"I know little about '{concept}' so far."

    def reflect_on_state(self) -> str:
        """
        Genesis's first-person account of its current cognitive state.

        Covers: what it has been focused on, what it understands well,
        what it is uncertain about, what it is actively trying to learn.
        Not a template — built from live graph and belief revision state.
        """
        lines: list[str] = []

        # ── What has been salient recently? ───────────────────────────
        try:
            latest = self._orch.consolidation.latest()
            if latest and latest.get("salient"):
                salient = latest["salient"][:5]
                lines.append(
                    f"Lately my attention has been on: {', '.join(salient)}."
                )
                # For the top concept, give a real explanation
                if salient:
                    explanation = self.explain(salient[0])
                    lines.append(explanation)
        except Exception:
            pass

        # ── What does Genesis understand well? ────────────────────────
        try:
            stats = self._orch.belief_revision.stats()
            n_provenance = stats.get("relations_with_provenance", 0)
            n_revised    = stats.get("beliefs_revised", 0)
            n_tensions   = stats.get("tensions_held", 0)

            if n_provenance > 0:
                lines.append(
                    f"I have tracked provenance on {n_provenance} belief(s). "
                    + (f"I have revised {n_revised} belief(s) when stronger "
                       f"evidence arrived. " if n_revised else "")
                    + (f"I am holding {n_tensions} contradiction(s) in tension, "
                       f"waiting for resolution." if n_tensions else "")
                )
        except Exception:
            pass

        # ── What is Genesis actively curious about? ───────────────────
        directives = self._orch.curiosity_directives()
        if directives:
            lines.append(
                f"I am actively trying to understand: {', '.join(directives[:5])}. "
                f"These are concepts I have encountered but cannot yet fully explain."
            )

        # ── Prediction error: what does Genesis know vs not know? ─────
        try:
            context = self._orch.memory._working._context_terms
            if context:
                pred_err = self._orch.relations.prediction_error(context[:6])
                if pred_err > 0.7:
                    lines.append(
                        f"My current prediction error is high ({pred_err:.2f}) — "
                        f"I am in territory I do not understand well yet."
                    )
                elif pred_err < 0.3:
                    lines.append(
                        f"My prediction error is low ({pred_err:.2f}) — "
                        f"I am in well-mapped territory."
                    )
        except Exception:
            pass

        if not lines:
            return "I am still building my understanding. There is not yet enough to reflect on."

        return "\n\n".join(lines)

    def revision_narrative(self, limit: int = 5) -> str:
        """
        What has Genesis changed its mind about, and why?
        Expressed as first-person account from the revision audit trail.
        """
        history = self._orch.belief_revision.revision_history(limit=limit)
        if not history:
            return "I have not yet revised any beliefs based on contradicting evidence."

        lines = ["Here is what I have changed my mind about:"]
        for h in history:
            subj, rel, obj = h["subject"], h["relation"], h["object"]
            old_c, new_c = h["old_confidence"], h["new_confidence"]
            reason = h.get("reason", "")
            lines.append(
                f"  I reduced my confidence that '{subj} {rel.lower()} {obj}' "
                f"from {old_c:.2f} to {new_c:.2f}. {reason[:120]}"
            )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Chain building
    # ------------------------------------------------------------------

    def _build_chains(self, concept: str) -> list[list[dict]]:
        """
        Find the longest causal chains starting from this concept.
        Returns up to 3 chains, each a list of relation dicts.
        """
        chains: list[list[dict]] = []
        queue: list[list[dict]] = [[]]

        # BFS from concept following CAUSES/CONTROLS/ENABLES edges
        _CHAIN_RELS = {"CAUSES", "CONTROLS", "ENABLES", "PREVENTS"}

        start = concept
        visited_in_chain: set[str] = {start}

        def extend(path: list[dict], from_concept: str, visited: set[str]) -> None:
            if len(path) >= _MAX_CHAIN:
                if len(path) >= 2:
                    chains.append(path)
                return
            rels = self._orch.relations.query_subject(from_concept, min_confidence=_MIN_CONF)
            found_extension = False
            for r in rels:
                if r["relation"] not in _CHAIN_RELS:
                    continue
                nxt = r["object"]
                if nxt in visited:
                    continue
                found_extension = True
                new_visited = visited | {nxt}
                step = {"from": from_concept, "relation": r["relation"],
                        "to": nxt, "confidence": r["confidence"]}
                extend(path + [step], nxt, new_visited)
            if not found_extension and len(path) >= 2:
                chains.append(path)

        extend([], start, {start})
        # Sort by length descending, then confidence
        chains.sort(
            key=lambda c: (len(c), sum(s["confidence"] for s in c)),
            reverse=True
        )
        return chains[:3]

    def _narrate_chain(self, chain: list[dict]) -> str:
        """Turn a chain of steps into a readable causal sentence."""
        if not chain:
            return ""
        parts = [chain[0]["from"]]
        for step in chain:
            rel_word = {
                "CAUSES":   "→ causes",
                "CONTROLS": "→ controls",
                "ENABLES":  "→ enables",
                "PREVENTS": "→ prevents",
            }.get(step["relation"], "→")
            parts.append(f"{rel_word} {step['to']}")
        return " ".join(parts)
